### ISSUE TITLE
Deploy tool is not supported in latest version of CLI

### ISSUE THREAD

**Issue by lifelogics1** [rahulmalhotra/SFDX-Deploy-Tool#10]
Dear , Thanks for nice tool. 

SFDX-Deploy-Tool  is  not supported for  current versions of CLI  like 2.67.7 win32-x64              ( node-v22.10.0 )

Error:

sf force:mdapi:retrieve -r "metadata" --target-org skyExpressDev -k "metadata\package.xml" # ERROR: Unable to convert this command; you must convert it manually.
 
»   Warning: force mdapi retrieve is not a sf command.
Did you mean force mdapi convert? (Y/n)

Regards, Mian Sarfraz

**Comment by lifelogics1** [comment]
Is someone looking into ?    as you know CLI has changed from SFDX to SF hence tool is no longer supported

**Comment by rahulmalhotra** [comment]
Hi Mian, I'm on it. Will share an update soon.
