### ISSUE TITLE
You don't need a test class to deploy to a Product environment

### ISSUE THREAD

**Issue by JasonZhuAtamation** [rahulmalhotra/SFDX-Deploy-Tool#3]
Since we mentioned to Salesforce that the test class is not required to be deployed to the Product case, now I can directly deploy metadata to the Product with vscode tool, but I still can't deploy metadata with the tool developed by you, because it needs the test class. Is there any way to bypass this restriction?

**Comment by rahulmalhotra** [comment]
Hi @JasonZhuAtamation which VSCode tool are you talking about? Test classes are mainly required when you're deploying to production. If you're deploying to a sandbox, test coverage is not required. You can set testLevel=NoTestRun in the [config.txt](https://github.com/rahulmalhotra/SFDX-Deploy-Tool/blob/master/config.txt) file for this and it should work fine

**Comment by rahulmalhotra** [comment]
Closing this issue as it's been over 30 days without any activity.
