### ISSUE TITLE
No test class deployed to the product environment

### ISSUE THREAD

**Issue by JasonZhuAtamation** [rahulmalhotra/SFDX-Deploy-Tool#5]
Since our org has asked salesforce to deploy the product environment without the test class, but using your tool I have to have the test class to deploy to the product environment, can you remove this validation, I think you have done the validation in advance when I deploy to the product environment.I was able to deploy directly to the product environment without any test classes using the Visual Studio Code tool developed by Microsoft.

**Comment by JasonZhuAtamation** [comment]
I have solved it, I just used the way to specify the test class, even though this test class has nothing to do with what I am deploying, but I just tested it and I can deploy the sanbox metadata to the product. Here it works provided that the validation that the test class is not needed is presented to salesforce.Your tools are so good, thank you very much!

**Comment by rahulmalhotra** [comment]
Usually, when we're using visual studio code for production deployment with salesforce extension pack, it run all the tests present in the org for every deployment. We can configure the same in our tool by mentioning **RunAllTestsInOrg** test level.
