### ISSUE TITLE
How to cancel deployment

### ISSUE THREAD

**Issue by JasonZhuAtamation** [rahulmalhotra/SFDX-Deploy-Tool#6]
When several people are deploying content to an org, and a person wants to interfere with the deployment, how should I cancel the deployment at this time

**Comment by rahulmalhotra** [comment]
Hi @JasonZhuAtamation 
We can cancel the deployment using "**sfdx force:mdapi:deploy:cancel**" command or "**sfdx force:mdapi:deploy:cancel -i <jobid>**" if we have a job id. This option is not present as a part of the tool currently, although it's a nice to have feature. I'll try to incorportate it asap.

**Comment by rahulmalhotra** [comment]
Hi @JasonZhuAtamation 
We can cancel the deployment using "**sfdx force:mdapi:deploy:cancel**" command or "**sfdx force:mdapi:deploy:cancel -i &lt;jobid&gt;**" if we have a job id. This option is not present as a part of the tool currently, although it's a nice to have feature. I'll try to incorportate it asap.

**Comment by JasonZhuAtamation** [comment]
Hi @rahulmalhotra 
Thank you very much for your reply, the tool you developed is very useful.

**Comment by JasonZhuAtamation** [comment]
Thank you very much. I'll close this ticket
